# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 13:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('body', models.CharField(max_length=140)),
                ('content', models.TextField()),
                ('genre', models.CharField(max_length=10)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 4, 16, 13, 51, 32, 324566))),
                ('publish', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('publishdate', models.DateTimeField()),
                ('content', models.TextField(max_length=140)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.Article')),
            ],
        ),
    ]
