# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
