# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 22:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 13, 22, 32, 50, 404193)),
        ),
    ]
