# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Articles.UserProfile'),
            preserve_default=False,
        ),
    ]
