# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 13:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_auto_20170416_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='publishdate',
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 16, 13, 58, 16, 646878)),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 16, 13, 58, 16, 646167)),
        ),
    ]
