# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_auto_20170506_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentToComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(max_length=140)),
                ('publish', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comcom',
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.CharField(max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='commenttocomment',
            name='com',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Articles.Comment'),
        ),
    ]
