# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_article_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='genre',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
