# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0003_auto_20170510_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenttocomment',
            name='com',
        ),
        migrations.AddField(
            model_name='comment',
            name='com',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Articles.CommentToComment'),
        ),
    ]
