# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0004_auto_20170510_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='com',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Articles.Comment'),
        ),
        migrations.DeleteModel(
            name='CommentToComment',
        ),
    ]
