# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0005_auto_20170510_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='com',
        ),
    ]
