# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='titlt', editable=False, max_length=60, unique=True),
            preserve_default=False,
        ),
    ]
