# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20171015_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='popularity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
